Create job to destroy an environment (#166)
Allows you to select an environment from the list and destroy it with Terraform

Also added a check to the env-destroy job to check if an environment is protected before destroying it

#minor

diff --git a/.github/workflows/env-destroy.yml b/.github/workflows/env-destroy.yml
--- a/.github/workflows/env-destroy.yml
+++ b/.github/workflows/env-destroy.yml
@@ -19,8 +19,19 @@ on:
         required: true
 
 jobs:
+  check:
+    name: Check
+    runs-on: ubuntu-latest
+    steps:
+      - name: Error if protected
+        if: ${{ contains(fromJSON('["development", "preproduction", "production", "demo"]'), inputs.workspace_name) }}
+        run: |
+          echo "Cannot destroy protected Environment"
+          exit 1
+
   terraform_environment_workflow:
     runs-on: ubuntu-latest
+    needs: check
     steps:
       - uses: actions/checkout@v4
         with:
